### ISSUE TITLE
Review Notebook - SiaPartners

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/AIFES#10]
Please review [the Notebook provided by Alliander](https://github.com/alliander-opensource/AIFES/blob/179718f5850d2f87f42cc9d5ab95ca2714d34071/project/00.Evaluate_performance_using_Backtest_Pipeline.ipynb) (which was a result of https://github.com/alliander-opensource/AIFES/issues/8).

Does the notebook work on your machine?
Is the content clear?
What additional functionality would be useful?

**Comment by MartijnCa** [comment]
Hi @dkunne-sia !
Just wanted to let you know that I added links to the notebook that needs a review and the relevant issue that Frank finished. Maybe you already finished the review. But if you have not had the chance to do so yet, then it should now be easier to find what you need to get started.

**Comment by dkunne-sia** [comment]
Wasn't able to run on own computer, due to access issues - but generally straightforward notebook. Well documented for the most parts with comments as guidance. 

Noticed only MAE is taken as metric, I would argue it is valuable to assess the RMSE as well, given it's nature to penalize larger errors more. Together, both metrics can be compared to assess the variance in the error distributions of the forecast.

Furthermore, a method to compare multiple forecast models (for one or more locations) in one notebook would be a potential improvement.
